version: '3.5'

services:
  back:
    build:
      context: ./ToDo.API
      dockerfile: Dockerfile
    ports:
      - 8084:80
    depends_on:
      - db
  front:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - BACKEND=back
    depends_on:
      - back
    links:
      - back
